version: '3'

services:
  otc-exporter:
    restart: always
    image: vitriolfox/otc-cloudeye-prometheus-exporter
    ports:
      - "8000:8000"
    environment:
      - REFRESH_TIME=300
      - NAMESPACES=ECS,DMS
      - PROJECT_ID=<projectid>
      - TENANT_NAME=OTC-EU-DE-<tenantnumber>
      - USERNAME=foo
      - PASSWORD=bar
      - LOG_LEVEL=DEBUG